accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
   


]

dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [

   
    path('verification/',views.label_creation,name='createlabel'),
    path('all/labels/',views.labels_list,name='labelslist'),
    path('label/all/view/<int:id>/',views.labels_view,name='userlabelview'),
    path('users/table/',views.view_my_label_table,name='stafflabeltable'),



]

macadmin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),#change url in production
    #path('',views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'WISTRON ADMINISTRATION'

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Q
import datetime 
import email
from datetime import date
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse
from label.models import Label
from accounts.forms import UserAddForm
from label.forms import LabelCreationForm
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
import time
from django.http import JsonResponse
# from label.forms import CommentForm






def label_creation(request):
	if not request.user.is_authenticated:
		return redirect('accounts:login')
	if request.method == 'POST':
		form = LabelCreationForm(data = request.POST)
		if form.is_valid():
			instance = form.save(commit = False)
			user = request.user
			instance.user = user
			employee_email=instance.user.email
			instance.save()
			time.sleep(5)
			return redirect("dashboard:createlabel")
	else:
		dataset = dict()
		form = LabelCreationForm()
		dataset['form'] = form
		dataset['title'] = 'Label Verification'
		return render(request,'dashboard/create_label.html',dataset)
	# return HttpResponse('label creation form')



 

def labels_list(request):
	if not (request.user.is_staff and request.user.is_superuser):
		return redirect('/')
	labels = Label.objects.all_pending_labels()
	#labels = Label.objects.filter(created=date.today())
	#time.sleep(3)
	return render(request,'dashboard/labels_recent.html',{'label_list':labels,'title':'labels list - pending'})



def labels_approved_list(request):
	if not (request.user.is_superuser and request.user.is_staff):
		return redirect('/')
	labels = Label.objects.all_approved_labels() #approved labels -> calling model manager method
	return render(request,'dashboard/labels_approved.html',{'label_list':labels,'title':'approved label list'})



def labels_view(request,id):
	if not (request.user.is_authenticated):
		return redirect('/')

	label = get_object_or_404(Label, id = id)
	
	return render(request,'dashboard/label_detail_view.html',{'label':label,'title':'{0}-{1} label'.format(label.user.username,label.status)})






def view_my_label_table(request):
	# work on the logics
	if request.user.is_authenticated:
		user = request.user
		labels = Label.objects.filter(user = user)
		print(labels)
		dataset = dict()
		dataset['label_list'] = labels
	
		dataset['title'] = 'Labels List'
	else:
		return redirect('accounts:login')
	return render(request,'dashboard/staff_labels_table.html',dataset)

templates/dashboard/create_label2.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	background: #eeeeee;
	font-family: 'Varela Round', sans-serif;
}
.navbar {
	color: black;
	background: #926dde !important;
	padding: 5px 16px;
	border-radius: 0;
	border: none;
	box-shadow: 0 0 4px rgba(0,0,0,.1);
}
.navbar img {
	border-radius: 50%;
	width: 36px;
	height: 36px;
	margin-right: 10px;
}
.navbar .navbar-brand {
	color: #efe5ff;
	padding-left: 0;
	padding-right: 50px;
	font-size: 24px;		
}
.navbar .navbar-brand:hover, .navbar .navbar-brand:focus {
	color: #fff;
}
.navbar .navbar-brand i {
	font-size: 25px;
	margin-right: 5px;
}
.search-box {
	position: relative;
}	
.search-box input {
	padding-right: 35px;
	min-height: 38px;
	border: none;
	background: #faf7fd;
	border-radius: 3px !important;
}
.search-box input:focus {		
	background: #fff;
	box-shadow: none;
}
.search-box .input-group-addon {
	min-width: 35px;
	border: none;
	background: transparent;
	position: absolute;
	right: 0;
	z-index: 9;
	padding: 10px 7px;
	height: 100%;
}
.search-box i {
	color: #a0a5b1;
	font-size: 19px;
}
.navbar .nav-item i {
	font-size: 18px;
}
.navbar .nav-item span {
	position: relative;
	top: 3px;
}
.navbar .navbar-nav > a {
	color: #efe5ff;
	padding: 8px 15px;
	font-size: 14px;		
}
.navbar .navbar-nav > a:hover, .navbar .navbar-nav > a:focus {
	color: #fff;
	text-shadow: 0 0 4px rgba(255,255,255,0.3);
}
.navbar .navbar-nav > a > i {
	display: block;
	text-align: center;
}
.navbar .dropdown-item i {
	font-size: 16px;
	min-width: 22px;
}
.navbar .dropdown-item .material-icons {
	font-size: 21px;
	line-height: 16px;
	vertical-align: middle;
	margin-top: -2px;
}
.navbar .nav-item.open > a, .navbar .nav-item.open > a:hover, .navbar .nav-item.open > a:focus {
	color: #fff;
	background: none !important;
}
.navbar .dropdown-menu {
	border-radius: 1px;
	border-color: #e5e5e5;
	box-shadow: 0 2px 8px rgba(0,0,0,.05);
}
.navbar .dropdown-menu a {
	color: #777 !important;
	padding: 8px 20px;
	line-height: normal;
	font-size: 15px;
}
.navbar .dropdown-menu a:hover, .navbar .dropdown-menu a:focus {
	color: #333 !important;
	background: transparent !important;
}
.navbar .navbar-nav .active a, .navbar .navbar-nav .active a:hover, .navbar .navbar-nav .active a:focus {
	color: #fff;
	text-shadow: 0 0 4px rgba(255,255,255,0.2);
	background: transparent !important;
}
.navbar .navbar-nav .user-action {
	padding: 9px 15px;
	font-size: 15px;
}
.navbar .navbar-toggle {
	border-color: #fff;
}
.navbar .navbar-toggle .icon-bar {
	background: #fff;
}
.navbar .navbar-toggle:focus, .navbar .navbar-toggle:hover {
	background: transparent;
}
.navbar .navbar-nav .open .dropdown-menu {
	background: #faf7fd;
	border-radius: 1px;
	border-color: #faf7fd;
	box-shadow: 0 2px 8px rgba(0,0,0,.05);
}
.navbar .divider {
	background-color: #e9ecef !important;
}
@media (min-width: 1200px){
	.form-inline .input-group {
		width: 350px;
		margin-left: 30px;
	}
}
@media (max-width: 1199px){
	.navbar .navbar-nav > a > i {
		display: inline-block;			
		text-align: left;
		min-width: 30px;
		position: relative;
		top: 4px;
	}
	.navbar .navbar-collapse {
		border: none;
		box-shadow: none;
		padding: 0;
	}
	.navbar .navbar-form {
		border: none;			
		display: block;
		margin: 10px 0;
		padding: 0;
	}
	.navbar .navbar-nav {
		margin: 8px 0;
	}
	.navbar .navbar-toggle {
		margin-right: 0;
	}
	.input-group {
		width: 100%;
	}
}
</style>
</head> 
<body>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
	<a href="#" class="navbar-brand"><i class="fa fa-cube"></i>Brand<b>Name</b></a>  		
	<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	<div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">		
		<form class="navbar-form form-inline">
			
		</form>
		<div class="navbar-nav ml-auto">
			<a href="#" class="nav-item nav-link active"><i class="fa fa-home"></i><span>Home</span></a>
			<a href="#" class="nav-item nav-link"><i class="fa fa-gears"></i><span>Projects</span></a>
			<a href="#" class="nav-item nav-link"><i class="fa fa-users"></i><span>Team</span></a>
			<a href="#" class="nav-item nav-link"><i class="fa fa-pie-chart"></i><span>Reports</span></a>
			<a href="#" class="nav-item nav-link"><i class="fa fa-briefcase"></i><span>Careers</span></a>
			<a href="#" class="nav-item nav-link"><i class="fa fa-envelope"></i><span>Messages</span></a>		
			<a href="#" class="nav-item nav-link"><i class="fa fa-bell"></i><span>Notifications</span></a>
			<div class="nav-item dropdown">
				<a href="#" data-toggle="dropdown" class="nav-item nav-link dropdown-toggle user-action"><img src="https://www.tutorialrepublic.com/examples/images/avatar/3.jpg" class="avatar" alt="Avatar"> Antonio Moreno <b class="caret"></b></a>
				<div class="dropdown-menu">
					<a href="#" class="dropdown-item"><i class="fa fa-user-o"></i> Profile</a>
					<a href="#" class="dropdown-item"><i class="fa fa-calendar-o"></i> Calendar</a>
					<a href="#" class="dropdown-item"><i class="fa fa-sliders"></i> Settings</a>
					<div class="divider dropdown-divider"></div>
					<a href="#" class="dropdown-item"><i class="material-icons">&#xE8AC;</i> Logout</a>
				</div>
			</div>
		</div>
	</div>
</nav>
</body>
</html>

templates/dashboard/label_detail_view.html
{%load static%}
<head>
	<meta charset="utf-8" />
	<link rel="icon"href="{% static 'img/favicon.png' %}"> 
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
  

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'css/demo.css' %}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body>


    <style type="text/css">
#back{
    background-color: rgb(27, 118, 238);
    color: #fff;
    width: max-content;
    height: max-content;
    font-size:x-large;
    margin-left: 30px;
    empty-cells: show;
    
}

   /* body{
        
       background: url('/static/img/mac.jpg');
       background-repeat: no-repeat;
       background-size: 40%;
       background-position: center;
       background-size: fixed;

    }
*/
        .title-h3{
        font-weight: bold;
        font-variant: petite-caps;
    }


     .sidebar{
    -webkit-box-shadow: 0 2px 2px 0 rgba(202, 255, 8, 0.904), 0 3px 1px -2px rgba(146, 230, 13, 0.815)0.12)12)12), 0 1px 5px 0 rgba(0,0,0,0.2);
     box-shadow: 0 2px 2px 0 rgba(218, 255, 6, 0.76)), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2); 
     transition: all 400ms ease-in;
    }
    
    .sidebar:hover{
        -webkit-box-shadow: 0 8px 17px 2px rgba(173, 247, 0, 0.979), 0 3px 14px 2px rgba(182, 247, 4, 0.12), 0 5px 5px -3px rgba(0,0,0,0.2);
    box-shadow: 0 8px 17px 2px rgb(80, 243, 5), 0 3px 14px 2px rgba(99, 255, 8, 0.918), 0 5px 5px -3px rgb(228, 224, 8);
    }


    .shadow{
        box-shadow:0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
     }

     a.simple-text{
        font-family: 'Russo One', sans-serif;
     }

      a.simple-text > span{
        font-size: 13px !important;
      }

      .logo a{
        font-family: 'sans-serif', bold;
      }

    .sub-title{
        vertical-align: -webkit-baseline-middle;
        font-size: 12px;
        font-family: 'sans-serif', bold;
    }


    tr td{
        font-variant: petite-caps;
    }

    .loader {
    position: fixed;
    z-index: 99;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: white;
    display: flex;
    justify-content: center;
    align-items: center;
}

.loader > img {
    width: 850px
}

.loader.hidden {
    animation: fadeOut 5s;
    animation-fill-mode: forwards;
}

@keyframes fadeOut {
    100% {
        opacity: 0;
        visibility: hidden;
    }
}

.thumb {
    height: 100px;
    border: 1px solid black;
    margin: 10px;
}




    .rounded-circle-image{
    border-radius: 50% !important;
    width:250px;
    height:250px;
  }

  .form-wrapper{
  background:#fff;
  -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);

  padding-top: 2rem;
  padding-bottom: 2rem;

}


.list-group {
  margin-top: 10px;
}

span{
  color: #6f6f6f;
  font-weight: lighter;
  font-size: 16px;
}


.list-group-item {
    position: relative;
    display: block;
    padding: 10px 15px;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid transparent;
    font-size:17px;
}

  #override-start{
    background:none !important;
    top: 35% !important;
    right:13px;
    color:#000;
    font-size: 24px;

    }

    .alert-warning{
        background:#fd7b7b;
    }

    .alert-success {
        background-color: #82b72a;
    }

    .alert-success,.alert-warning{
        font-size:16px;
    }

    .employee-name-title{
    color: #3873b1;
    font-weight: 600;
    font-variant: petite-caps;
    font-size: 3.1rem !important;
  }

  span,.list-group-item > div{
  font-variant: petite-caps;
}


.panel-default>.panel-heading {
    color: #fff !important;
    background-color: #2d88a9 !important;
}

.panel-title a:hover{
  color:#e6e4e4;
}

.panel-title a:active{
  color:#e6e4e4;
}

.panel-title a:focus{
  color:#e6e4e4;
}



{% block stylesheet %}
     
     
     {% endblock %}
     </style>


  

 {% block content %}
 <a href="{% url 'dashboard:labelslist' %}" id="back" >Back</a>
        <section class="content">
            <section class="container-fluid">
           
                <section class="form-wrapper">
                    <section class="row">
                        <section class="col col-lg-8 col-md-12  col-sm-12">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

          

                    <section class="row">
                       
                        <section class="col-lg-8 col-md-12 col-sm-12">
                            
                                    <div class="list-group" id="list-tab" role="tablist">
                                        
                                            <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Verifier_Name</span> <div>{{ label.user }}</div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Supplier_Label</span> <div>{{label.supplierlabel}}|{{label.s_trace}}|{{label.s_quantity}}|{{label.s_id}}|{{label.s_name}}  </div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Wistron_Label</span><div>{{label.wistronlabel}}|{{label.w_trace}}|{{label.w_quantity}}|{{label.w_id}}|{{label.w_name}} </div>
                                            </a>

                                            </a>
                                          

                                             </a>

                                       
                                      </div>

                        </section>
                    </section>


                             
                                  <span style="font-size: 13px;padding-left: 1rem;" class="pull-left">Created {{ label.created }}</span>
                              


                </section>

            </section> <!-- /container --> 
        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}

{% endblock %}
</script>

templates/dashboard/staff_labels_table.html
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> 
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  </head>
  <style type="text/css">
        .alert-warning{
        background:#fd7b7b;
    }

    .alert-success {
        background-color: #82b72a;
    }
 

  .body{
   position: relative;

  }
  #button{
    margin-left: 210px;
  }
  #id{
    padding-block: 10px;
  
  }
  .a{
   
  }
  .child1{
       border: 2px solid;
      width: 500px;
      height: 510px;
      display: inline-block;
    position: fixed;
   
   border-color: rgb(227, 25, 93);
   
    
  }
  #input1{
      width: 350px;
      height: 50px;
      margin-top: 6%;
      margin-left: 15%;
      border-color: rgb(255, 0, 85);
  }
  
  #input2{
     
      width: 350px;
      height: 50px;
      margin-top: 9%;
      margin-left: 15%;
      border-color: rgb(255, 0, 85);
  }
  #input3{
      
      width: 350px;
      height: 50px;
      margin-top: 10%;
      margin-left: 15%;
      border-color: rgb(255, 0, 85);
  } 
  #input4{
     
      width: 350px;
      height: 50px;
      margin-top: 11%;
      margin-left: 15%;
      border-color: rgb(255, 0, 85);
  }
  
  #input5{
      
      width: 350px;
      height: 50px;
      margin-top: 6%;
      margin-left: 15%;
      border-color: rgb(255, 0, 85);
  }
  .child2{
      border:2px solid black;
      width: 500px;
      height: 510px;
      display: inline-block;
      position: fixed;
      overflow-x: hidden;  
      border-style: ridge;
      border-color: rgb(227, 25, 93);
  }
  #input6{
     
      width: 350px;
      height: 50px;
      margin-top: 9%;
      margin-left: 15%;
      border-color: rgb(255, 0, 85);
  }
  #input7{
      
      width: 350px;
      height: 50px;
      margin-top: 10%;
      margin-left: 15%;
      border-color: rgb(255, 0, 85);
  } 
  #input8{
     
      width: 350px;
      height: 50px;
      margin-top: 11%;
      margin-left: 15%;
      border-color: rgb(255, 0, 85);
  }
  body {
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }
    
    .topnav {
      overflow: hidden;
      background-color: #ac0379;
    }
    
    .topnav a {
      float: left;
      color: #f2f2f2;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-size: 17px;
    }
    
    .topnav a:hover {
      background-color: #cb2771;
      color: rgb(86, 2, 41);
    }
    
    .topnav a.active {
      background-color: rgb(116, 71, 102);
      color: white;
    }
    #mn{
          color: white;
      }   
      table, th, td {  
  border: 1px solid black;  
  border-collapse: collapse;  
 text-align: center;
 
}  
th{
  background-color: #82b72a;
  font-family: Georgia, 'Times New Roman', Times, serif;
 
}
  

  </style>
  
  </style>
  <body onload="display_ct();" class="body">
    
    
    <div class="topnav">
		{%if request.user.is_superuser%}
      <a href="{% url 'dashboard:stafflabeltable' %}" class="pull-left">All_Labels</a>
	  {%endif%}
    <a href="{% url 'dashboard:createlabel' %}" class="pull-left"   >Back</a>
     <a href="#" class="fa fa-user" style="margin-left: 1090px; font-weight: bolder ;" >{{request.user}}</a>
     <a href="{% url 'accounts:logout'  %}" class="pull-right" style="background-color: rgb(255, 0, 85) ;">Log_out</a>
     
    </div>
        <!--CONTENTS-->
 {% block content %}
        <section class="content">
            

                	<!-- TABLE -->
                	<div class="table-responsive table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3" style="color: #60a0b3 !important;
    						text-shadow: 1px 0px rgba(0,0,0,0.11)"></h4>
                		</div>
                   <input type="text" id="searchInput" placeholder="Search...">

                		{% if label_list %}
                		<table id="myTable" class="table">
							<thead>
							  <tr >
								<center> <th scope="col">S.NO</th> </center>
							<center>	<th scope="col">User</th></center>
              <center><th scope="col">Supplier_Label</th></center>
							<center>	<th scope="col">Wistron_Label</th></center>
								
							  </tr>
							</thead>
							<tbody >
								{% for label in label_list %}
							  <tr>
                              <center> <td>{{forloop.counter}}</td></center>
							<center>	<td>{{ label.user }}</td></center>
							<center>	<td>{{label.supplierlabel}}|{{label.s_trace}}|{{label.s_quantity}}|{{label.s_id}}|{{label.s_name}}   </td></center>
						<center>		<td>{{label.wistronlabel}}|{{label.w_trace}}|{{label.w_quantity}}|{{label.w_id}}|{{label.w_name}} </td></center>


				</tr>

							    {% endfor %}

							  </tbody>

						</table>
						{% else %}

						<span>No Requests can be found...</span>
						{% endif %}
			
					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">

$(document).ready(function () {
    $("#searchInput").on("keyup", function () {
        var value = $(this).val().toLowerCase();
        $(".table").each(function () {
            $(this).find("tr").each(function () {
                if ($(this).text().toLowerCase().indexOf(value) > -1) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
        });
    });
});
</script>